# Generated by Django 3.2.15 on 2022-08-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('taxNumber', models.CharField(blank=True, default='', max_length=100)),
                ('registrationNumber', models.CharField(blank=True, default='', max_length=100)),
                ('specialization', models.CharField(blank=True, default='', max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
