name: Build

on:
  push:
    branches:
      - main

jobs:
 deploy:
   name: Deploy
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v1
     - uses: actions-hub/gcloud@master
       env:
         PROJECT_ID: ${{secrets.PYTHON_PROD_ID}}
         APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_GITHUB_CREDENTIALS}}
       with:
         args: app deploy app.yaml